export const AVATAR_CLICK = 'AVATAR_CLICK';
export const USER_NAME_TYPED = 'USER_NAME_TYPED';
export const LOGIN_BUTTON_STATE_CHANGE =  'LOGIN_BUTTON_STATE_CHANGE';
export const LOGIN_CLICK = "LOGIN_CLICK";