export const AVATAR_CLICK = 'AVATAR_CLICK';
export const USER_NAME_TYPED = 'USER_NAME_TYPED';
export const SHOW_INVALID_ALERT = 'SHOW_INVALID_ALERT';
export const ENABLE_LOGIN_BUTTON = 'ENABLE_LOGIN_BUTTON';
export const LOGIN_CLICK = "LOGIN_CLICK";
export const SAVE_AVATAR_COLLECTION = 'SAVE_AVATAR_COLLECTION';